apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllers-swagger-deployment
  labels:
    app: controllers-swagger
spec:
  template:
    spec:
      containers:
        - name: controllers-swagger
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: secret-dbs-env
                  key: MONGO_URL
