apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllers-authorization-deployment
  labels:
    app: controllers-authorization
spec:
  template:
    spec:
      containers:
        - name: controllers-authorization
          envFrom:
            - configMapRef:
                name: controllers-environment-dev
